services:
  app:
    build: 
      context: .
      dockerfile: backend/Dockerfile
    ports:
      - "9595:9595"
    volumes:
      - ./data:/app/data
      - /var/run/docker.sock:/var/run/docker.sock
    environment:
      - PYTHONUNBUFFERED=1
