version: '3.8'
services:
  app:
    build: 
      context: .
      dockerfile: backend/Dockerfile
    ports:
      - "9595:9595"
    volumes:
      - ./backend/ports.csv:/app/ports.csv
      - /var/run/docker.sock:/var/run/docker.sock
    environment:
      - PYTHONUNBUFFERED=1
