services:
  portdashboard:
    build: 
      context: .
      dockerfile: backend/Dockerfile
    container_name: portdashboard
    environment:
      - PYTHONUNBUFFERED=1
    volumes:
      - ./data:/app/data
      - /var/run/docker.sock:/var/run/docker.sock
    ports:
      - "9595:9595"
    restart: unless-stopped